name: rac_portfolio_update

on:
  push:
    branches:
      - main  # Change this if you want to trigger on another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}   # Replace with your actual S3 bucket name
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'ap-southeast-1'  # Change this to your AWS region
